<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [1]:
import numpy as np
array1 = np.arange(0,10,1)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [2]:
array2 = np.reshape(array1, (2,5))
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [3]:
lista_array3 = [0, 2, 0, 3, 0, 4, 0]
array3 = np.array(lista_array3)
distinto_0 = np.where(array3 > 0)
distinto_0

(array([1, 3, 5]),)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [4]:
array4 = np.random.randint(0, 2, (3,3))
array4

array([[1, 0, 1],
       [0, 0, 1],
       [0, 1, 1]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [5]:
array5 = np.random.rand(10)
minimo = np.min(array5)
maximo = np.max(array5)
print (array5)
print (minimo)
print (maximo)

[0.86204645 0.51607972 0.37220453 0.35524457 0.64050707 0.2790565
 0.11754514 0.72050042 0.65851988 0.59207582]
0.11754514102094105
0.8620464472602023


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [6]:
array6 = np.arange(0,9,1)
print(array6)
invertido = -np.sort(-array6)
print (invertido)

[0 1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1 0]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [7]:
array7 = np.random.randint(1, 24, (2,3,4))
print(array7)
primer15 = np.where(array7 == 15)
print("---------")
print (primer15)
print("---------")
print (array7[0,:, :])
print("---------")
print (array7[1,2, :])

[[[23 18  9 14]
  [16  8  6 15]
  [19  6  6 22]]

 [[13 10  5  2]
  [22 10 12 11]
  [19 12 19 23]]]
---------
(array([0]), array([1]), array([3]))
---------
[[23 18  9 14]
 [16  8  6 15]
 [19  6  6 22]]
---------
[19 12 19 23]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [8]:
array8 = np.random.randint(1, 30, (3,2,5))
print(array8)
print("---------")
print (array8[0,0:2,0:2])
print("---------")
print (array8[1:3, :, :])

[[[ 9 21 13 10 10]
  [29 13 10 20 23]]

 [[24 17  7  1 28]
  [25  8 20 17 28]]

 [[ 7 24 25 13 29]
  [28 14 29  3 22]]]
---------
[[ 9 21]
 [29 13]]
---------
[[[24 17  7  1 28]
  [25  8 20 17 28]]

 [[ 7 24 25 13 29]
  [28 14 29  3 22]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [9]:
array9 = np.random.randint(1, 24, (4,3,2))
print (array9)
print("---------")
array9[1][1][:] = 0
array9[3][:][:] = -1
print (array9)

[[[21  1]
  [ 4  2]
  [18  2]]

 [[10 15]
  [ 8 20]
  [20 13]]

 [[ 6 19]
  [ 2 17]
  [16 15]]

 [[12  9]
  [22 16]
  [21 11]]]
---------
[[[21  1]
  [ 4  2]
  [18  2]]

 [[10 15]
  [ 0  0]
  [20 13]]

 [[ 6 19]
  [ 2 17]
  [16 15]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [10]:
array10 = np.random.randint(-10, 13, (2,4,3))
print(array10)
print("--------")
mayor5 = np.where(array10 > 5)
print(mayor5)
print("--------")
negativos = np.where(array10 < 0, 0, array10)
print(negativos)


[[[  8  -5   2]
  [ -3  -3   8]
  [ -3  10  -4]
  [ -8  -7  -5]]

 [[ -4   4  -4]
  [  5  11  -3]
  [ -9  -7  -5]
  [-10   4  12]]]
--------
(array([0, 0, 0, 1, 1]), array([0, 1, 2, 1, 3]), array([0, 2, 1, 1, 2]))
--------
[[[ 8  0  2]
  [ 0  0  8]
  [ 0 10  0]
  [ 0  0  0]]

 [[ 0  4  0]
  [ 5 11  0]
  [ 0  0  0]
  [ 0  4 12]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [11]:
array11 = np.random.randint(1, 27, (3,3,3))
print(array11)
print("----------")
print(array11[1, :, 0:2])
print("----------")
mayor20 = np.where(array11[2,:,:] > 20)
print(mayor20)

[[[ 2 14  8]
  [24  5  3]
  [16  7 21]]

 [[17  7 12]
  [11 18  9]
  [24 20  2]]

 [[14 25 22]
  [17 14 23]
  [ 2 25  5]]]
----------
[[17  7]
 [11 18]
 [24 20]]
----------
(array([0, 0, 1, 2]), array([1, 2, 2, 1]))


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [12]:
array12 = np.random.rand(10)
print(array12)
print("------------")
min = np.min(array12)
max = np.max(array12)
array12mod = np.where([(array12 == max) | (array12 == min)], 0.00, array12) 
print(array12mod)

[5.12098135e-02 2.32546888e-01 4.66284820e-01 6.33713752e-01
 7.94269555e-01 4.79186868e-01 4.25982963e-01 9.46421524e-01
 3.15264666e-01 7.64504813e-04]
------------
[[0.05120981 0.23254689 0.46628482 0.63371375 0.79426955 0.47918687
  0.42598296 0.         0.31526467 0.        ]]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [13]:
array13 = np.random.randint(1,100,15)
print(array13)
print("-----------")
array13ord = np.sort(array13)
print(array13ord)

[44 57 43 99 13 55 27 30 99 62 58 88 93 45  8]
-----------
[ 8 13 27 30 43 44 45 55 57 58 62 88 93 99 99]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [14]:
array14 = np.random.randint(0, 17, (4,4))
print(array14)
print("------------")
suma_columnas = np.sum(array14, axis = 0)
suma_filas = np.sum(array14, axis =1)
print(suma_columnas)
print(suma_filas.reshape(4,1))

[[ 6 12 14 13]
 [10  5 13  0]
 [ 7  4 11  2]
 [ 0  1  2 12]]
------------
[23 22 40 27]
[[45]
 [28]
 [24]
 [15]]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [15]:
array15 = np.zeros((5,5))
array15 [:,0:1] = 1
array15 [:,4:5] = 1
print(array15)

[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [16]:
array16 = np.random.rand(10)
media = np.mean(array16)
desviacion = np.std(array16)
print(array16)
print("----------")
print(media)
print(desviacion)

[0.59999979 0.4800758  0.03585155 0.83052622 0.93048516 0.81046122
 0.80111693 0.708793   0.17736209 0.98865006]
----------
0.6363321812111764
0.30133989536444133


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [17]:
array17 = np.random.randint(1, 24, (2,3,4))
print(array17)
print("-----------")
array17_trans = np.transpose(array17, (2,1,0))
print(array17_trans)

[[[ 4  2  5 21]
  [12 23 12 23]
  [ 7 17 18 23]]

 [[ 4 17  8  8]
  [ 7 18 18 13]
  [16 15 15 11]]]
-----------
[[[ 4  4]
  [12  7]
  [ 7 16]]

 [[ 2 17]
  [23 18]
  [17 15]]

 [[ 5  8]
  [12 18]
  [18 15]]

 [[21  8]
  [23 13]
  [23 11]]]


El método transpose cambia el orden de la matriz según queramos. Para ello tenemos que indicar el orden en el que queremos poner los ejes en la nueva matriz según su posición. Es decir, siguiendo la estructura (matriz, filas, columnas) deberemos indicar qué es lo que queremos cambiar a cada una de las posiciones. En este ejemplo tenemos una matriz (2,3,4) y queremos una nueva con forma (4,3,2) por lo que tenemos que indicar que en la matriz queremos el valor 4 que se encuentra en la posicion 2, en filas queremos el valor 3 que se encuentra en la posicion 1 y en columnas queremos el valor 2 que se encuentra en la posicion 0, por tanto debemos indicar (2,1,0).

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [18]:
array18 = np.random.randint(1, 24, (3,4,2))
print(array18)
print("----------")
array18_swp = np.swapaxes(array18, 0,1)
print(array18_swp)

[[[ 6 10]
  [19  2]
  [20  6]
  [13 21]]

 [[11  5]
  [ 3 15]
  [22  3]
  [19  4]]

 [[20  5]
  [12 15]
  [ 7 17]
  [ 7 16]]]
----------
[[[ 6 10]
  [11  5]
  [20  5]]

 [[19  2]
  [ 3 15]
  [12 15]]

 [[20  6]
  [22  3]
  [ 7 17]]

 [[13 21]
  [19  4]
  [ 7 16]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [19]:
array19 = np.random.randint(1, 24, (3,2,4))
array19_v = np.transpose(array19, (2,0,1))
print(array19)
print("---------")
print(array19_v)

[[[ 6 21  9  1]
  [ 1 21 22 18]]

 [[16 19 23  3]
  [ 7  5 16 19]]

 [[15 13  8  8]
  [12 16 15 17]]]
---------
[[[ 6  1]
  [16  7]
  [15 12]]

 [[21 21]
  [19  5]
  [13 16]]

 [[ 9 22]
  [23 16]
  [ 8 15]]

 [[ 1 18]
  [ 3 19]
  [ 8 17]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [20]:
array20 = np.random.randint(-10, 10, (3,4,5), dtype = int)
array_vacio  = np.empty((3, 4, 5), dtype = object)
mediana = np.median(array20)
max = np.max(array20)
min = np.min(array20)
array_vacio = np.where(array20 == mediana, "M", array20)
array_vacio = np.where(array20>= mediana,  "X", array_vacio)
array_vacio = np.where(array20 <= mediana, "Y", array_vacio)
array_vacio = np.where(array20 == min, "MIN", array_vacio)
array_vacio = np.where(array20 == max, "MAX", array_vacio)
array_vacio


array([[['Y', 'X', 'Y', 'Y', 'X'],
        ['Y', 'X', 'X', 'X', 'X'],
        ['Y', 'Y', 'Y', 'Y', 'X'],
        ['X', 'Y', 'MAX', 'Y', 'Y']],

       [['X', 'Y', 'Y', 'Y', 'X'],
        ['X', 'Y', 'X', 'X', 'Y'],
        ['Y', 'X', 'Y', 'Y', 'Y'],
        ['X', 'X', 'Y', 'Y', 'X']],

       [['X', 'X', 'X', 'X', 'MAX'],
        ['MAX', 'Y', 'X', 'X', 'MIN'],
        ['MIN', 'Y', 'MAX', 'Y', 'Y'],
        ['Y', 'Y', 'X', 'MIN', 'Y']]], dtype='<U11')

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [21]:
array21 = np.random.randint(1, 3, (2,4,4))
print(array21)
for x in range(len(array21)):
    for f in range(array21.shape[1]):
        fila = array21[x, f, :]
        for c in range(array21.shape[0]):
            columna = array21[x, :, c]
            if np.all(fila == columna):
                print (f"si, la fila {fila} es igual que la columna {columna}")


[[[1 2 2 1]
  [1 2 1 2]
  [1 1 2 2]
  [1 2 2 2]]

 [[2 1 2 1]
  [1 2 1 2]
  [2 1 2 2]
  [2 2 1 2]]]
si, la fila [1 2 1 2] es igual que la columna [1 2 1 2]
si, la fila [2 1 2 2] es igual que la columna [2 1 2 2]
